# Generated by Django 4.2.10 on 2024-07-01 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, related_name='chat', to='messenger.message'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
