# Generated by Django 4.2.10 on 2024-07-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(blank=True, default='def_channel.png', null=True, upload_to='channel_avat'),
        ),
    ]
