# Generated by Django 4.2.10 on 2024-07-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='def_avatar.png', null=True, upload_to='avatars'),
        ),
    ]
